---
- name: Linux Client setup
  hosts: workstation
  become: yes
  gather_facts: yes

  tasks:

    - name: Deploy general linux client settings
      include_tasks:
        file: tasks/linux-client/system-setup.yml

    - name: Deploy Arch Linux packages with pacman  
      include_tasks:
        file: tasks/linux-client/pacman-packages.yml

    - name: Deploy Flatpak packages
      include_tasks:
        file: tasks/linux-client/flatpak-packages.yml

    - name: Deploy zsh settings
      include_tasks:
        file: tasks/linux-client/zsh-config.yml

    - name: Deploy alacritty settings
      include_tasks:
        file: tasks/linux-client/alacritty-config.yml

    - name: Deploy tmux settings
      include_tasks:
        file: tasks/linux-client/tmux-config.yml

    - name: Deploy gnome settings and themes
      include_tasks:
        file: tasks/linux-client/gnome-config.yml