---
- name: Get current username
  set_fact:
    current_user: "{{ lookup('env', 'USER') }}"

- name: clone alacritty theme repository
  git:
    repo: https://github.com/alacritty/alacritty-theme
    dest: /home/{{ current_user }}/.config/alacritty/themes/
    force: yes

- name: copy alacritty config
  copy:
    src: files/alacritty/alacritty.yml
    dest: /home/{{ current_user }}/.config/alacritty/alacritty.yml
    owner: "{{ current_user }}"
    group: "{{ current_user }}"
    mode: 0600