---
- name: Get current username
  set_fact:
    current_user: "{{ lookup('env', 'USER') }}"

- name: Check if the alacritty themes directory exists
  stat:
    path: "/home/{{ current_user }}/.config/alacritty/themes"
  register: alacritty_themes_installed

- name: clone alacritty themes
  git:
    repo: https://github.com/alacritty/alacritty-theme
    dest: /home/{{ current_user }}/.config/alacritty/
    force: yes
  when: not alacritty_themes_installed.stat.exists

- name: copy alacritty config
  copy:
    src: files/alacritty/alacritty.yml
    dest: /home/{{ current_user }}/.config/alacritty/alacritty.yml
    owner: "{{ current_user }}"
    group: "{{ current_user }}"
    mode: 0600
    force: no

- name: adapt the alacritty desktop file to always start in wayland
  lineinfile:
    path: /usr/share/applications/Alacritty.desktop
    regexp: '^Exec=alacritty'
    line: 'Exec=env -u WAYLAND_DISPLAY alacritty'