---
- name: Get current username
  set_fact:
    current_user: "{{ lookup('env', 'USER') }}"

- name: install gnome-extensions-cli
  become: no
  become_user: "{{ username }}"
  community.general.pipx:
    name: gnome-extensions-cli
    system_site_packages: true

- name: Check if gext is installed
  command: "which gext"
  register: gext_check