---
- name: Get current username
  set_fact:
    current_user: "{{ lookup('env', 'USER') }}"

- name: install gnome-extensions-cli
  community.general.pipx:
    name: gnome-extensions-cli
    system-site_packages: true

- name: Check if gext is installed
  command: "which gext"
  register: gext_check