---
- name: system setup | cron | install cron package
  tags: packages,cron
  package:
    name:
      - cronie
    state: latest

- name: system setup | cron | start and enable cronie daemon
  tags: cron
  service:
    name: cronie
    state: started
    enabled: true

- name: Check if Meslo font directory exists
  stat:
    path: "/usr/share/fonts/Meslo"
  register: meslo_font_status

- name: Create Meslo directory if not exists
  file:
    path: /usr/share/fonts/Meslo
    state: directory

- name: Download Meslo Nerd Font
  unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/Meslo.zip
    dest: "/usr/share/fonts/Meslo"
    remote_src: yes
  when: meslo_font_status.stat.exists == false

- name: Check if Inter font directory exists
  stat:
    path: "/usr/share/fonts/inter"
  register: inter_font_status

- name: Install Inter font if not present
  package:
    name: inter-font
    state: present
  when: inter_font_status.stat.exists == false

- name: Set Inter font as interface font
  community.general.dconf:
    key: "/org/gnome/desktop/interface/font-name"
    value: "'Inter Light 11'"

- name: Update Font cache 
  command: fc-cache -fvdconf

- name: Set Inter font as document font
  community.general.dconf:
    key: "/org/gnome/desktop/interface/document-font-name"
    value: "'Inter Light 11'"

- name: Set Inter font as titlebar font
  community.general.dconf:
    key: "/org/gnome/desktop/wm/preferences/titlebar-font"
    value: "'Inter Bold 11'"

- name: Set Meslo as Terminal font
  community.general.dconf:
    key: "/org/gnome/desktop/interface/monospace-font-name"
    value: "'MesloLGS Nerd Font 10'"

- name: Uncomment the line in /etc/locale.gen
  lineinfile:
    path: /etc/locale.gen
    regexp: '^#de_AT.UTF-8 UTF-8'
    line: 'de_AT.UTF-8 UTF-8'

- name: Update locales 
  command: locale-gen

- name: Set locales with community.general.dconf
  community.general.dconf:
    key: "/system/locale/region"
    value: "'de_AT.UTF-8'"

- name: Add NoDisplay=true to unused desktop files
  ansible.builtin.blockinfile:
    path: "/usr/share/applications/{{ item }}"
    block: |
      NoDisplay=true
    with_items:
      - avahi-discover.desktop
      - bssh.desktop
      - bvnc.desktop
      - lstopo.desktop
      - htop.desktop
      - qv4l2.desktop
      - qvidcap.desktop
      - vim.desktop
      - org.gnome.Tour.desktop
      - yelp.desktop

- name: Get current username
  set_fact:
    current_user: "{{ lookup('env', 'USER') }}"
    
- name: Copy profile image
  copy:
    src: files/user/profile.png
    dest: "/var/lib/AccountsService/icons/{{ current_user }}"
    owner: root
    group: root
    mode: 0644

- name: users | set profile image
  lineinfile:
    path: "/var/lib/AccountsService/users/{{ current_user }}"
    regexp: '^Icon=.*'
    line: 'Icon=/var/lib/AccountsService/icons/{{ current_user }}'
    state: present