---
#################
### Variables ###
#################

- name: Get current username
  set_fact:
    current_user: "{{ lookup('env', 'USER') }}"

- name: Check if Inter font directory exists
  stat:
    path: "/usr/share/fonts/inter"
  register: inter_font_status

- name: Check if Meslo font directory exists
  stat:
    path: "/usr/share/fonts/Meslo"
  register: meslo_font_status

- name: enable gnome extensions
  become: no
  become_user: "{{ current_user }}"
  shell: "gnome-extensions enable {{ item }}"
  with_items:
    - "logomenu@aryan_k"
    - "user-theme@gnome-shell-extensions.gcampax.github.com"
    - "espresso@coadmunkee.github.com"
    - "gsconnect@andyholmes.github.io"
    - "blur-my-shell@aunetx"
    - "clipboard-indicator@tudmotu.com"
    - "just-perfection-desktop@just-perfection"

#######################
### dconf setttings ###
#######################

- name: disable weather service location
  dconf:
    key: "/org/gnome/calendar/weather-settings"
    value: false

- name: show all input sources
  dconf:
    key: "/org/gnome/desktop/input-sources/show-all-sources"
    value:  true

- name: Set Inter font as interface font
  dconf:
    key: "/org/gnome/desktop/interface/font-name"
    value: "'Inter Light 11'"

- name: Set Inter font as document font
  dconf:
    key: "/org/gnome/desktop/interface/document-font-name"
    value: "'Inter Light 11'"

- name: Set Inter font as titlebar font
  dconf:
    key: "/org/gnome/desktop/wm/preferences/titlebar-font"
    value: "'Inter Bold 11'"

- name: Set Meslo as Terminal font
  dconf:
    key: "/org/gnome/desktop/interface/monospace-font-name"
    value: "'MesloLGS Nerd Font 10'"

- name: set color scheme
  become_user: "{{ current_user }}"
  dconf:
    key: "/org/gnome/desktop/interface/color-scheme"
    value: "'prefer-dark'"

- name: set cursor theme
  become_user: "{{ current_user }}"
  dconf:
    key: "/org/gnome/desktop/interface/cursor-theme"
    value: "'WhiteSur-cursors'"

- name: set icon theme
  become_user: "{{ current_user }}"
  dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'Colloid-Dark'"

- name: set user theme
  become_user: "{{ current_user }}"
  dconf:
    key: "/org/gnome/shell/extensions/user-theme/name"
    value: "'Colloid-Dark'"

- name: set shell theme
  become_user: "{{ current_user }}"
  dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Colloid-Dark'"

- name: button-layout
  become_user: "{{ current_user }}"
  dconf:
    key: "/org/gnome/desktop/wm/preferences/button-layout"
    value: "':minimize,maximize,close'"

- name: enable-hot-corners
  become_user: "{{ current_user }}"
  dconf:
    key: "/org/gnome/desktop/interface/enable-hot-corners"
    value: "false"

- name: clock-show-weekday
  become_user: "{{ current_user }}"
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-weekday"
    value: "true"

- name: clock-show-seconds
  become_user: "{{ current_user }}"
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-seconds"
    value: "true"

- name: clock-show-weekdate
  become_user: "{{ current_user }}"
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-weekdate"
    value: "true"
  
- name: enable tap-to-click
  become_user: "{{ current_user }}"
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
    value: "true"

- name: disable reboot/shutdown countdown
  become_user: "{{ current_user }}"
  dconf:
    key: "/org/gnome/gnome-session/logout-prompt"
    value: "false"

- name: show-battery-percentage
  become_user: "{{ current_user }}"
  dconf:
    key: "/org/gnome/desktop/interface/show-battery-percentage"
    value: "true"

- name: enable natural scrolling (mouse)
  become_user: "{{ current_user }}"
  dconf:
    key: "/org/gnome/desktop/peripherals/mouse/natural-scroll"
    value: "false"

- name: enable natural scrolling (touchpad)
  become_user: "{{ current_user }}"
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll"
    value: "true"

- name: enable cursor acceleration (mouse)
  become_user: "{{ current_user }}"
  dconf:
    key: "/org/gnome/desktop/peripherals/mouse/accel-profile"
    value: "'adaptive'"

##########################
### Logo Menu Settings ###
##########################

- name: set arch logo 
  become_user: "{{ current_user }}"
  dconf:
    key: "/org/gnome/shell/extensions/Logo-menu/menu-button-icon-image"
    value: "6"

- name: set arch logo size
  become_user: "{{ current_user }}"
  dconf:
    key: "/org/gnome/shell/extensions/Logo-menu/menu-button-icon-size"
    value: "20"

- name: set menu terminal 
  become_user: "{{ current_user }}"
  dconf:
    key: "/org/gnome/shell/extensions/Logo-menu/menu-button-terminal"
    value: "'alacritty'"

- name: set menu system-monitor 
  become_user: "{{ current_user }}"
  dconf:
    key: "/org/gnome/shell/extensions/Logo-menu/menu-button-system-monitor"
    value: "'btop'"

- name: show activities buttton 
  become_user: "{{ current_user }}"
  dconf:
    key: "/org/gnome/shell/extensions/Logo-menu/show-activities-button"
    value: "true"

- name: hide icon shadow
  become_user: "{{ current_user }}"
  dconf:
    key: "/org/gnome/shell/extensions/Logo-menu/hide-icon-shadow"
    value: "true"

###########################
### Clipboard Indicator ###
###########################

#####################
### Blur My Shell ###
#####################

################
### Espresso ###
################

########################
### Just Perfection ####
########################

#############################
### Nautilus File Browser ###
#############################

######################
### Gnome Terminal ###
######################
