---
- name: Get current username
  set_fact:
    current_user: "{{ lookup('env', 'USER') }}"

- name: Check if install-gnome-extensions directory already exists
  stat:
    path: "/home/{{ current_user }}/projects/install-gnome-extensions"
  register: ige_status

- name: clone ige repository
  become_user: "{{ current_user }}"
  git:
    repo: https://github.com/ToasterUwU/install-gnome-extensions.git
    dest: /home/{{ current_user }}/projects/install-gnome-extensions
  when: ige_status.stat.exists == false

- name: make ige script executable
  file:
    dest: /home/{{ current_user }}/projects/install-gnome-extensions/install-gnome-extensions.sh
    mode: +x
    owner: "{{ current_user }}"
    group: "{{ current_user }}"

- name: copy gnome-extensions file to project directory
  copy:
    src: files/gnome-extensions/extension-list.txt
    dest: /home/{{ current_user }}/projects/install-gnome-extensions/extension-list.txt
    owner: "{{ current_user }}"
    group: "{{ current_user }}"

- name: install gnome extensions
  become: no
  become_user: "{{ current_user }}"
  shell: "sh /home/{{ current_user }}/projects/install-gnome-extensions/install-gnome-extensions.sh --enable --file /home/{{ current_user }}/projects/install-gnome-extensions/extension-list.txt"

#- name: install gnome-extensions-cli
#  become: no
#  become_user: "{{ current_user }}"
#  community.general.pipx:
#    name: gnome-extensions-cli
#    system_site_packages: true
#
#- name: source .zsh files again
#  become: no
#  become_user: "{{ current_user }}"
#  shell: "source ~/.zshenv && source ~/.config/zsh/.zshrc"
#  args:
#    executable: /bin/zsh
#
#- name: Check if gext is installed
#  shell: "which gext"
#  args:
#    executable: /bin/zsh
#  register: gext_check
#
#- name: install a list of gnome extensions
#  shell: "gext install {{ item }}"
#  args:
#    executable: /bin/zsh
#  with_items:
#    - "user-theme@gnome-shell-extensions.gcampax.github.com"
#    - "logomenu@aryan_k"
#    - "just-perfection-desktop@just-perfection"
#    - "espresso@coadmunkee.github.com"
#    - "gsconnect@andyholmes.github.io"
#    - "blur-my-shell@aunetx"
#    - "clipboard-indicator@tudmotu.com"
#  when: gext_check.rc == 1

- name: check if the theme directory exists
  stat:
    path: "/home/{{ current_user }}/.themes/Colloid"
  register: colloid_installed

- name: clone colloid gtk theme
  become: no
  become_user: "{{ current_user }}"
  git:
    repo: https://github.com/vinceliuice/Colloid-gtk-theme.git
    dest: "/home/{{ current_user }}/projects/gnome-theming/colloid-gtk-theme"
    force: yes
  when: not colloid_installed.stat.exists

- name: install colloid gtk theme
  become: no
  become_user: "{{ current_user }}"
  command: "/home/{{ current_user }}/projects/gnome-theming/colloid-gtk-theme/install.sh --color dark --libadwaita --tweaks rimless"
  when: not colloid_installed.stat.exists

- name: Check if the icon directory exists
  stat:
    path: /home/{{ current_user }}/projects/gnome-theming/colloid-icon-theme
  register: colloid_icons_installed

- name: clone colloid icon theme
  become: no
  become_user: "{{ current_user }}"
  git:
    repo: https://github.com/vinceliuice/Colloid-icon-theme.git
    dest: /home/{{ current_user }}/projects/gnome-theming/colloid-icon-theme
    force: yes
  when: not colloid_icons_installed.stat.exists

- name: install colloid icon them
  become: no
  become_user: "{{ current_user }}"
  command: /home/{{ current_user }}/projects/gnome-theming/colloid-icon-theme/install.sh
  when: not colloid_icons_installed.stat.exists

- name: Check if the cursor directory exists
  stat:
    path: /home/{{ current_user }}/projects/gnome-theming/whiteSur-cursors
  register: whitesur_cursors_installed

- name: clone cursor themes
  git:
    repo: https://github.com/vinceliuice/WhiteSur-cursors.git
    dest: /home/{{ current_user }}/projects/gnome-theming/whitesur-cursors
    force: yes
  when: not whitesur_cursors_installed.stat.exists

- name: install white sur cursors
  become: no
  become_user: "{{ current_user }}"
  command: /home/{{ current_user }}/projects/gnome-theming/whitesur-cursors/install.sh
  when: not whitesur_cursors_installed.stat.exists

- name: Create cron job to sync gnome settings
  cron:
    name: sync-gnome-settings-and-extensions
    job: "ansible-pull --url https://github.com/augerl/ansible-deployment.git gnome-settings-pb.yml"
    special_time: reboot
    user: "{{ current_user }}"